nohup: ignoring input
using gpu:6 to train the model
using gpu:6 to train the model
cuda:6
Namespace(A_split=False, JK='sum', a_fold=100, aggregate=False, alpha=0.5, batch_size=1024, beta_inter=0.4, conv_layers=4, cuda=True, decay_epoch=10, device=device(type='cuda', index=6), device_id='6', domains='game_video', dropout=0.5, epoch=80, feature_dim=126, hidden_dim=126, inter_tau=0.2, intra_tau=1, lambda_critic=0.4, leakey=0.05, load=False, log='logs.txt', log_epoch=1, lr=0.004, lr_decay=0.95, min_epoch=50, mode='train', model_file=None, model_name='gv', momentum=0.9, num_latent_factors=3, num_negative=100, optim='adam', patience=30, proj_layers=1, projection=1, residual=1, save=False, save_dir='./saved_models', seed=2040, similarity_tau=0.1, test_sample_number=999, transfer_epoch=40, user_batch_size=256, weight_decay=0.0002)
number_user 25025
number_item 12319
/home/disk2/lhr/invariantCDR/invariantCDR/utils/GraphMaker.py:45: RuntimeWarning: divide by zero encountered in power
  r_inv = np.power(rowsum, -1).flatten()
real graph loaded!
number_user 19457
number_item 8751
real graph loaded!
graph loaded!
Loading data from game_video with batch size 1024...
unseen test: 0
test length: 1381
unseen test: 0
test length: 1304
unseen test: 0
test length: 1435
unseen test: 0
test length: 1458
source_user_num 25025
target_user_num 19457
source_item_num 12319
target_item_num 8751
shared users id: 1737
test users 226, 217
unseen test: 0
dev length: 1000
unseen test: 0
dev length: 1000
source train data : 155036, target train data: 156091, source test data : 1304, target test data : 1458, source dev data : 1000, target dev data : 1000
2024-08-03 04:29:33.440683: step 304/24320 (epoch 1/80), loss = 1.376710 (83.191 sec/epoch), lr: 0.004000
Evaluating on dev set...
..........Traceback (most recent call last):
  File "main.py", line 75, in <module>
    results = runner.train()
  File "/home/disk2/lhr/invariantCDR/invariantCDR/runner.py", line 239, in train
    s_mrr, s_ndcg_5, s_ndcg_10, s_hr_1, s_hr_5, s_hr_10 = self.predict(self.source_valid_batch, 1)
  File "/home/disk2/lhr/invariantCDR/invariantCDR/runner.py", line 168, in predict
    predictions = self.source_predict(batch)
  File "/home/disk2/lhr/invariantCDR/invariantCDR/runner.py", line 141, in source_predict
    score = self.recmodel.source_predict_dot(user_feature, item_feature)
  File "/home/disk2/lhr/invariantCDR/invariantCDR/model/invariantCDR.py", line 119, in source_predict_dot
    output = (user_embedding * item_embedding).sum(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 6; 23.69 GiB total capacity; 3.14 GiB already allocated; 110.94 MiB free; 3.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
